### ISSUE TITLE
Build failed on centos:7

### ISSUE THREAD

**Issue by tannevaled** [systemd/systemd-netlogd#22]
Hi,

i just tried to compile on CentOS 7.6 with the following .gitlab-ci.yml
```yaml
image: centos:7

systemd-netlogd:
  stage: build
  variables:
    REPOSITORY: https://github.com/systemd/systemd-netlogd
  script:
  - yum -y install git sudo
  - sudo yum -y install epel-release
  - sudo yum -y group install 'Development Tools'
  - sudo yum -y install gperf libcap-devel systemd-devel meson python34-sphinx
  - sudo git clone ${REPOSITORY}
  - cd systemd-netlogd
  - sudo make
  - sudo make install
  - sudo useradd -r -d / -s /usr/sbin/nologin -g systemd-journal systemd-journal-netlog
```
it failed with
```bash
...
Program sphinx-build-3 found: YES (/bin/sphinx-build-3)
Found pkg-config: /bin/pkg-config (0.27.1)
Native dependency libsystemd found: NO found '219' but need: '>= 230'

meson.build:142:0: ERROR:  Invalid version of dependency, need 'libsystemd' ['>= 230'] found '219'.

A full log can be found at /builds/phymath/systemd-netlogd/systemd-netlogd/build/meson-logs/meson-log.txt
make: *** [build] Error 1
ERROR: Job failed: exit code 1
```
is libsystemd version >=230 really needed?
is CentOS 7.6.1810 supported?

Thanks in advance for the answer
